spring.application.name=catalog-order-service

server.port=8080

spring.datasource.url=jdbc:h2:mem:catalogdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.sql.init.mode=always

app.api-key=${API_KEY:test-key}