CREATE TABLE products (
                          id BIGINT PRIMARY KEY,
                          name VARCHAR(255) NOT NULL,
                          price DECIMAL(10, 2) NOT NULL,
                          stock_quantity INT NOT NULL,
                          category VARCHAR(100)
);

CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        customer_email VARCHAR(255) NOT NULL,
                        created_at TIMESTAMP NOT NULL,
                        status VARCHAR(50) NOT NULL,
                        idempotency_key VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE order_items (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id BIGINT NOT NULL REFERENCES orders(id),
                             product_id BIGINT NOT NULL REFERENCES products(id),
                             quantity INT NOT NULL,
                             unit_price DECIMAL(10, 2) NOT NULL
);

CREATE INDEX idx_orders_created_at_id
    ON orders(created_at, id);

CREATE INDEX idx_order_items_order_product
    ON order_items(order_id, product_id);